### ISSUE TITLE
Add a command to send a bunch of "interesting" players

### ISSUE THREAD

**Issue by nick-strohm** [saltminede/saltychat-ragemp-js#2]
I would love to see a command similiar to the `BulkUpdate` command, which takes an array of `PlayerStates` and does not just "update" players but just unmutes a certain set of players and keep everybody else (not listed) muted.
This would give the possibility to not send (and keep track of) every client, but only send the players which are interesting for the local player.

An example code would be:
```ts
playerStateUpdate(): void {
    let playerPosition = mp.players.local.position;
    let playerUpdates = [];
    this.voiceClients.forEach((voiceClient, playerId) => {
        if (!mp.player.exists(voiceClient.player)) {
            return;
        }

        let otherPosition = voiceClient.player.position;
        let distance = mp.game.gameplay.getDistanceBetweenCoords(playerPosition.x, playerPosition.y, playerPosition.z, otherPosition.x, otherPosition.y, otherPosition.z, true);
        if (distance > VoiceRanges[voiceClient.voiceRange]) {
            return;
        }

        playerUpdates.push(new PlayerState(voiceClient.teamSpeakName, voiceClient.player.position, null, voiceClient.voiceRange, voiceClient.isAlive, null, false, null));
    });

    this.executeCommand(new PluginCommand(Command.BulkCommunication, this.serverUniqueIdentifier, { "Players": playerUpdates }));
}
```

**Comment by BlackFlash5** [comment]
That's what `DistanceCulling` is for.
If a player is distance culled, he will be ignored in the proximity calculation and muted, unless he's on a call or radio.

Btw: This isn't the place to request plugin commands. You can open feature requests in the docs repo.
